#IfWinActive, Move Or Die
F7::
Send, ApollozBasicallyIDoWRKCarmichaelCarnageD4D20DaithiDeNoglaDRKendoGavinH2ODeliriousJackJacobLinckeJakeJeremyJimmyKappaLirikMichaelMrHappyNicoPapaFrankuRawrSnacksReneeRyanSamSideArmsWrenXelu